const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.HTMLElement,
		C3.Plugins.Button,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.LoadObjectTexturesByName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{darek: 0},
	{moneda: 0},
	{matias: 0},
	{torres: 0},
	{Solid: 0},
	{Sprite: 0},
	{monedas: 0},
	{textovidas: 0},
	{Text2: 0},
	{Text3: 0},
	{play: 0},
	{HTMLElement: 0},
	{Button: 0},
	{Button2: 0},
	{Text4: 0},
	{Text5: 0},
	{Bullet: 0},
	{AntiDarek: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{moneda2: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Text6: 0},
	{mENUPRINCIPAL: 0},
	{BOTONpausa: 0},
	{continuar: 0},
	{tiedna: 0},
	{Button3: 0},
	{Text7: 0},
	{Text8: 0},
	{Text9: 0},
	{compramatias: 0},
	{alejandragratis: 0},
	{Text10: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{BanderaFinal: 0},
	{pasastenivel: 0},
	{Text: 0},
	{vidas: 0},
	{cameraOffsetY: 0},
	{cameraOffsetX: 0},
	{personajeSeleccionado: 0},
	{personaje1: 0},
	{PersonajesDesbloqueados: 0}
];

self.InstanceType = {
	darek: class extends self.ISpriteInstance {},
	moneda: class extends self.ISpriteInstance {},
	matias: class extends self.ISpriteInstance {},
	torres: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	monedas: class extends self.ITextInstance {},
	textovidas: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	play: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	AntiDarek: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	moneda2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	mENUPRINCIPAL: class extends self.IButtonInstance {},
	BOTONpausa: class extends self.IButtonInstance {},
	continuar: class extends self.IButtonInstance {},
	tiedna: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	compramatias: class extends self.IButtonInstance {},
	alejandragratis: class extends self.IButtonInstance {},
	Text10: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	BanderaFinal: class extends self.ISpriteInstance {},
	pasastenivel: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {}
}